name: CD

on:
  push:
    branches:
      - 'main'
      - 'feature/39-local-docker-build'

# Grant permissions to obtain federated identity credentials
# see https://docs.github.com/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

jobs:

  # Build runtime image in Azure Container Registry, tagged with the commit ID.
  Build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Build Docker runtime image
      - name: 'Build image'
        run: docker build -t data-dashboard:$(git rev-parse HEAD) .

      # Verify docker image
      - name: 'Verify image'
        run: |
          docker run -p 8080:80 -d --rm data-dashboard:$(git rev-parse HEAD)
          curl -f localhost:8080
